[package]
name = "ironrdp"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
byteorder = "1.5.0"
bytes = "1.4.0"
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
getrandom = { version = "0.2", features = ["js"] }
ironrdp-session.workspace = true
ironrdp-pdu.workspace = true
ironrdp-graphics.workspace = true
js-sys = "0.3.61"
log = "0.4.20"
time = { version = "0.3", features = ["wasm-bindgen"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["time"] }
tracing-web = "0.1.2"
wasm-bindgen = "0.2.84"
wasm-logger = "0.2.0"
web-sys = { version = "0.3.61", features = ["ImageData"] }
