name: Build CentOS 7 Buildbox Assets Images
run-name: Build CentOS 7 Buildbox Assets Images
on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * 0' # At 1:00 PM UTC every Sunday

env:
  REGISTRY: ghcr.io

jobs:
  buildbox-centos7-assets:
    name: Build CentOS 7 Asset Buildbox
    # Build assets on x86 for now, as no GHA-hosted runner for ARM64.
    runs-on: ubuntu-22.04-32core

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Teleport
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c # v3.1.0
        with:
          driver: docker

      - name: Login to registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # We need to keep env vars in sync, so, we can't use standard build actions
      - name: Build and push buildbox assets image
        run: cd build.assets && make build-centos7-assets PUSH=1
